name: Docker Publish Workflow

on:
  workflow_call:   # This makes the workflow reusable

    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ inputs.image_tag }} .
          docker push ghcr.io/${{ github.repository }}:${{ inputs.image_tag }}
