# Resusable GitHub Actions workflow to build and push a Docker image to GitHub Container Registry (GHCR)

name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'           # Trigger workflow on tag creation
  workflow_dispatch:    # Allows manual trigger from the GitHub UI

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Determine Docker tags
      - name: Determine Docker tags
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          fi
          echo "LATEST_TAG=latest" >> $GITHUB_ENV

      # Step 5: Build and tag the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} \
                       -t ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }} .

      # Step 6: Push the Docker image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}
          docker push ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}
